local function dl()
  term.clear()
  term.setCursorPos(1,1)
end
print("installing")
fs.makeDir("disk/assets")
fs.makeDir("disk/apps")
dl()
print("installing 1/6")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/startup.lua")
fs.move("startup.lua","disk/")
dl()
print("installing 2/6")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/menu.lua")
fs.move("menu.lua","disk/")
dl()
print("installing 3/6")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/assets/bg1.nfp")
fs.move("bg1.nfp","disk/assets/")
dl()
print("installing 4/6")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/assets/logo.nfp")
fs.move("logo.nfp","disk/assets/")
dl()
print("installing 5/6")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/assets/bg2.nfp")
fs.move("bg2.nfp","disk/assets/")
dl()
print("installing 6/7")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/apps/test.lua")
dl()
print("installing 7/7")
shell.run("wget https://raw.githubusercontent.com/HambatEverett/BluDOS/refs/heads/main/disk/apps/test2.lua")
dl()
term.setTextColor(colors.blue)
print("installed BluDOS")
sleep(2)
shell.run("rm install.lua")
os.reboot()
