term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
local bg = paintutils.loadImage("disk/assets/bg2.nfp")
paintutils.drawImage(bg,1,1)
term.setCursorPos(1,1)
term.setTextColor(colors.orange)
term.setBackgroundColor(colors.orange)
print("###################################################")
