local bg = paintutils.loadImage("disk/assets/bg1.nfp")
local logo = paintutils.loadImage("disk/assets/logo.nfp")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
paintutils.drawImage(bg,1,1)
paintutils.drawImage(logo,1,1)
sleep(1)
shell.run("disk/menu.lua")
